---
#- hosts: 192.168.12.81, 192.168.12.82, 192.168.12.83, 192.168.12.86, 192.168.12.87,  192.168.12.89, 192.168.12.90,  192.168.12.92,  192.168.12.93, 192.168.12.97, 192.168.12.98, 192.168.12.101, 192.168.12.100  #192.168.12.84, 192.168.12.85, 192.168.12.88, 192.168.12.99,  192.168.12.94, 192.168.12.95, 192.168.12.96, 192.168.12.91,
- hosts: 192.168.12.81, 192.168.12.82, 192.168.12.83, 192.168.12.86, 192.168.12.87, 192.168.12.88, 192.168.12.89, 192.168.12.90, 192.168.12.91, 192.168.12.92, 192.168.12.93, 192.168.12.94, 192.168.12.95, 192.168.12.96, 192.168.12.97, 192.168.12.98, 192.168.12.99, 192.168.12.101, 192.168.12.100  #192.168.12.84, 192.168.12.85,
  #strategy: free    
  remote_user: videk
  tasks:
  - name: Creates directory
    file:
      path: /home/videk/deploy 
      state: directory

  - name: deploy repo changes
    synchronize:
      src: "{{ lookup('env','PWD') }}"
      dest: /home/videk/deploy
      delete: yes
      recursive: yes
  

  - name: build docker file
    command: docker build -t vesna-drivers .
    args:
      chdir: /home/videk/deploy/vesna-drivers

  - name: cleanup docker containers
    register: target
    ignore_errors: yes
    command: "{{ item }}"
    with_items:
      - docker kill target
      - docker rm target

    # Root node
  - name: run docker image root
    command: docker run -d --name target --privileged --net=host -it -e TEST=Tests/system/alh -e TARGET=stats_app_root -e VESNA_DEV=/dev/ttyS2  vesna-drivers
    when: inventory_hostname == '192.168.12.86'

  - name: run docker image
    command: docker run -d --name target --privileged --net=host -it -e TEST=Tests/system/alh -e TARGET=stats_app -e VESNA_DEV=/dev/ttyS2 vesna-drivers
    when: inventory_hostname != '192.168.12.86'
