---
- hosts: 192.168.12.81, 192.168.12.83
  remote_user: videk

# Select which application to test, duration in minutes and which device should be the root of the network
  vars:
    application: 07_multicast
    duration: 3
    root_node: 192.168.12.83

# Display experiment abstract in build.log 
  tasks:
  - name: Display abstract
    debug:
      msg: "Testing {{application}}, duration {{duration}} minutes, root node is {{root_node}}"
    when: inventory_hostname == root_node

  - name: Create directory
    file:
      path: ~/LOG-a-TEC-testbed
      state: directory

# Unpack image from server
  - name: Unpack received docker image
    command: docker load -i ~/Docker-image.tar

  - name: Cleanup old docker containers (target)
    register: target
    ignore_errors: yes
    command: "{{ item }}"
    with_items:
      - docker kill target
      - docker rm target

    # Root node
  - name: Run docker image for root
    command: docker run -d --name target --privileged --net=host -it -e TARGET=run_experiment_root -e APP_DIR="{{application}}" -e APP_DURATION_MIN="{{duration}}" vesna-drivers
    when: inventory_hostname == root_node

    # Other nodes
  - name: Run docker image
    command: docker run -d --name target --privileged --net=host -it -e TARGET=run_experiment_node -e APP_DIR="{{application}}" -e APP_DURATION_MIN="{{duration}}" vesna-drivers
    when: inventory_hostname != root_node
