---
- hosts: 192.168.12.81
  remote_user: videk
  tasks:
  - name: Create directory
    file:
      path: ~/LOG-a-TEC-testbed
      state: directory

# recursive will also download the submodules
# on the version param you can change which branch to pull  TODO
  - name: Pull all changes from github
    git:
      repo: git@github.com:logatec3/LOG-a-TEC-testbed.git
      dest: ~/LOG-a-TEC-testbed
      recursive: yes
      update: yes
      version: master

# -f flag so we can later copy whole LOG-a-TEC directory into container
# with Dockerfile command COPY...else we get error "Forbidden path outside the build context"
  - name: Build docker file
    command: docker build -t vesna-drivers -f ~/LOG-a-TEC-testbed/deploy/docker/Dockerfile .
    args:
      chdir: ~/LOG-a-TEC-testbed

  - name: Cleanup old docker containers (target)
    register: target
    ignore_errors: yes
    command: "{{ item }}"
    with_items:
      - docker kill target
      - docker rm target

    # Root node
  #- name: Run docker image for root
  #  command: docker run -d --name target --privileged --net=host -it -e TARGET=run_experiment_root -e APP_DIR=00_hello-world -e APP_DURATION_MIN=60 vesna-drivers
  #  when: inventory_hostname == '192.168.12.86'

    # Other nodes
  - name: Run docker image
    command: docker run -d --name target --privileged --net=host -it -e TARGET=run_experiment_node -e APP_DIR=00_hello-world -e APP_DURATION_MIN=60 vesna-drivers
    when: inventory_hostname != '192.168.12.86'
