---
- hosts: 172.17.0.1
  remote_user: videk
  tasks:
  - name: Create directory
    file:
      path: ~/LOG-a-TEC-testbed
      state: directory

# recursive will also download the submodules
# on the version param you can change which branch to pull TODO
  - name: Pull all changes from github
    git:
      repo: git@github.com:logatec3/LOG-a-TEC-testbed.git
      dest: ~/LOG-a-TEC-testbed
      recursive: no
      update: yes
      version: master
      
# -f flag so we can later copy whole LOG-a-TEC directory into container
# with Dockerfile command COPY...else we get error "Forbidden path outside the build context"
  - name: Build docker file
    command: docker build -t vesna-drivers -f ~/LOG-a-TEC-testbed/deploy/docker/Dockerfile .
    args:
      chdir: ~/LOG-a-TEC-testbed

  - name: Cleanup old docker container (controller)
    ignore_errors: yes
    command: "{{ item }}"
    with_items:
      - docker kill controller
      - docker rm controller

  - name: Run docker image
    command: docker run --privileged --name controller -e TARGET=run_server -e NODES_NUM=1 -p 50000:50000 vesna-drivers 
