---
#############################################################################################################
# COLLECT RESULTS
#############################################################################################################
# Ansible playbook script that obtains results from devices and forwards them back to IMBA.
#
# Before deploying an experiment, select:
#
#   *) Participating nodes - MUST correspond to hosts from release_targets.yml
#
#############################################################################################################

- hosts: SRDA
  remote_user: videk
  
  vars:
    technology: srda

  tasks:
    - name: Stop the container
      ignore_errors: yes
      command: docker stop target-{{ technology }}

    - name: Copy file from the container
      command: docker cp target-{{ technology }}:/root/logatec-experiment/results/ .
      args:
        chdir: ~/deploy/logatec-experiment

    - name: Fetch measured data and log files to the out folder
      ignore_errors: yes
      synchronize:
        src: "{{ item }}"
        dest: ../../../out/
        mode: pull
      with_items: 
        - "~/deploy/logatec-experiment/results/*.txt"
        - "~/deploy/logatec-experiment/results/*.log"
  
    - name: Delete results from the device
      file: 
        path:  ~/deploy/logatec-experiment/results
        state: absent




#############################################################################################################
# CONTROLLER CLEANUP
#############################################################################################################
# Ansible playbook script that collect ECMS controller logs and cleans up the controller container.
#
############################################################################################################

- hosts: videk_server
  remote_user: videk
  
  vars:
    technology: srda

  tasks:
    - name: Stop controller and obtain logging file
      ignore_errors: yes
      command: "{{ item }}"
      with_items:
        - docker kill controller-{{ technology }}
        - docker cp controller-{{ technology }}:/root/logatec-experiment/ECMS_controller.log .
        - docker rm controller-{{ technology }}
      args:
        chdir: ~/deploy/logatec-experiment
  
    - name: Fetch logging file to the out folder
      synchronize:
        src: ~/deploy/logatec-experiment/*.log
        dest: ../../../out/
        mode: pull
  
    - name: Delete results from server
      file: 
        path:  ~/deploy/logatec-experiment/*.log
        state: absent
  
