---
#############################################################################################################
# RELEASE TARGETS
#############################################################################################################
# Ansible playbook script that deploys experiment application to the testbed nodes.
#
# Before deploying an experiment, select:
#
#   *) Participating nodes    - by entering their technology or a cluster name under the hosts variable. 
#                               Cluster names are defined in the /inventory/logatec_testbed file.
#                               Adding ":&sna-lgtc-192-168-12" will include only active devices. 
#   *) Experiment application - by entering application folder name under the application variable.
#   *) Experiment duration    - by entering minutes to the duration variable.
#   *) Additional options     - default is none. monitor applies ECMS service.                     
#
#############################################################################################################

- hosts: SRDB_template:&sna-lgtc-192-168-12
  strategy: free
  remote_user: videk

  vars:
    technology: srdb
    application: 00_hello-world
    duration: 20
    option: monitor

  tasks:
    - name: Create directory
      file:
        path: ~/deploy
        state: directory

    - name: Deploy experiment repository
      synchronize:
        src: "{{ lookup('env','PWD') }}"
        dest: ~/deploy
        delete: yes
        recursive: yes
  
    - name: Build the docker file
      command: docker build -t logatec-experiment-srd -f deployment/docker/Dockerfile . 
      args:
        chdir: ~/deploy/logatec-experiment
  
    - name: Cleanup old docker containers
      ignore_errors: yes
      command: "{{ item }}"
      with_items:
        - docker kill target-{{ technology }}
        - docker rm target-{{ technology }}
  
    - name: Run docker container
      command: docker run --name target-{{technology}} --privileged --net=host -e APP="{{application}}" -e APP_DUR="{{duration}}" -e OPTION="{{option}}" logatec-experiment-srd
  
